### ISSUE TITLE
cyberark.github.io/helm-charts is getting 404

### ISSUE THREAD

**Issue by AbdulmelikKalkan** [cyberark/helm-charts#21]
## Summary
Github pages of helm chart is getting 404. so I couldn't add helm repo

![image](https://user-images.githubusercontent.com/49363216/120592203-1e4c3e00-c446-11eb-9a71-9c23d22c87c0.png)

**Comment by izgeri** [comment]
Thanks for flagging this @AbdulmelikKalkan - we're looking into it now.

**Comment by izgeri** [comment]
@AbdulmelikKalkan this should be resolved now - can you please confirm? Once you do, we'll close this issue. Thanks again for reporting it!

**Comment by AbdulmelikKalkan** [comment]
Hi @izgeri 

It solved, Thank you
